<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-04-28T07:29:37Z" name="Suite" finished-at="2020-04-28T07:30:05Z" duration-ms="28392">
    <groups>
    </groups>
    <test started-at="2020-04-28T07:29:37Z" name="Test" finished-at="2020-04-28T07:29:46Z" duration-ms="9116">
      <class name="Destiny.testCases.HomePage">
        <test-method is-config="true" signature="initialize()[pri:0, instance:Destiny.testCases.HomePage@4f74980d]" started-at="2020-04-28T07:29:37Z" name="initialize" finished-at="2020-04-28T07:29:45Z" duration-ms="8063" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="ValidationHomePage()[pri:0, instance:Destiny.testCases.HomePage@4f74980d]" started-at="2020-04-28T07:29:45Z" name="ValidationHomePage" finished-at="2020-04-28T07:29:45Z" duration-ms="261" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at Destiny.testCases.HomePage.ValidationHomePage(HomePage.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidationHomePage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Destiny.testCases.HomePage@4f74980d]" started-at="2020-04-28T07:29:46Z" name="tearDown" finished-at="2020-04-28T07:29:46Z" duration-ms="111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Destiny.testCases.HomePage -->
    </test> <!-- Test -->
    <test started-at="2020-04-28T07:29:46Z" name="Test01" finished-at="2020-04-28T07:30:05Z" duration-ms="19213">
      <class name="Destiny.testCases.LoginPage">
        <test-method is-config="true" signature="initialize()[pri:0, instance:Destiny.testCases.LoginPage@1fd14d74]" started-at="2020-04-28T07:29:46Z" name="initialize" finished-at="2020-04-28T07:29:53Z" duration-ms="7398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="Login()[pri:0, instance:Destiny.testCases.LoginPage@1fd14d74]" started-at="2020-04-28T07:29:53Z" name="Login" finished-at="2020-04-28T07:30:05Z" duration-ms="11698" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Destiny.testCases.LoginPage@1fd14d74]" started-at="2020-04-28T07:30:05Z" name="tearDown" finished-at="2020-04-28T07:30:05Z" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Destiny.testCases.LoginPage -->
    </test> <!-- Test01 -->
  </suite> <!-- Suite -->
</testng-results>
